# Generated by Django 2.1.11 on 2020-01-21 14:41

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("career", "0001_initial"),
        ("career", "0002_auto_20140923_0007"),
        ("career", "0003_auto_20141121_2006"),
        ("career", "0004_auto_20141121_2014"),
        ("career", "0005_auto_20141121_2015"),
        ("career", "0006_auto_20141121_2054"),
        ("career", "0007_joblisting_frontpage"),
        ("career", "0007_auto_20150130_1925"),
        ("career", "0008_merge"),
        ("career", "0009_auto_20150922_1818"),
        ("career", "0010_joblisting_hide_contactinfo"),
        ("career", "0010_auto_20161004_1437"),
        ("career", "0011_merge_20171229_1651"),
        ("career", "0012_auto_20171229_1747"),
        ("career", "0013_auto_20171231_1831"),
        ("career", "0014_auto_20180329_2111"),
        ("career", "0015_auto_20180728_1850"),
        ("career", "0016_auto_20181008_1529"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Joblisting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(editable=False)),
                ("date_saved", models.DateTimeField(editable=False)),
                ("title", models.CharField(max_length=160, verbose_name="title")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (b"si", "Summer internship"),
                            (b"pp", "Permanent position"),
                            (b"bi", "Bad import"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="joblistings/",
                        verbose_name="image",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="deadline"),
                ),
                ("from_year", models.PositiveIntegerField(default=1)),
                ("to_year", models.PositiveIntegerField(default=5)),
                ("url", models.URLField(blank=True, verbose_name="url")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joblistings",
                        to="company.Company",
                        verbose_name="company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.CompanyContact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joblisting_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joblisting_saved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(editable=False)),
                ("date_saved", models.DateTimeField(editable=False)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="town_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="town_saved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="joblisting",
            name="towns",
            field=models.ManyToManyField(
                blank=True, null=True, to="career.Town", verbose_name="town"
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="deadline"),
        ),
        migrations.RenameField(
            model_name="joblisting",
            old_name="from_year",
            new_name="from_year",
        ),
        migrations.AlterModelOptions(
            name="joblisting",
            options={"ordering": ("-deadline",)},
        ),
        migrations.AddField(
            model_name="joblisting",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="frontpage",
            field=models.BooleanField(default=False, verbose_name="Frontpage"),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="from_year",
            field=models.PositiveIntegerField(default=1, verbose_name="from year"),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="to_year",
            field=models.PositiveIntegerField(default=5, verbose_name="to year"),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="type",
            field=models.CharField(
                choices=[(b"si", "Summer internship"), (b"pp", "Permanent position")],
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AlterModelOptions(
            name="joblisting",
            options={"ordering": ("deadline",)},
        ),
        migrations.AddField(
            model_name="joblisting",
            name="hide_contactinfo",
            field=models.BooleanField(default=False, verbose_name="Hide contact info"),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="joblistings/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="type",
            field=models.CharField(
                choices=[("si", "Summer internship"), ("pp", "Permanent position")],
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="towns",
            field=models.ManyToManyField(
                blank=True, to="career.Town", verbose_name="town"
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.CompanyContact",
                verbose_name="contact",
            ),
        ),
        migrations.AlterModelOptions(
            name="joblisting",
            options={"base_manager_name": "objects", "ordering": ("deadline", "pk")},
        ),
        migrations.AlterModelManagers(
            name="joblisting",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
