# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("career", "0011_merge_20171229_1651")]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="towns",
            field=models.ManyToManyField(
                blank=True, to="career.Town", verbose_name="town"
            ),
        )
    ]
