# Generated by Django 2.1.2 on 2018-10-08 13:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_auto_20180728_1850'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='joblisting',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
