# Generated by Django 2.1.11 on 2020-01-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("career", "0016_auto_20181008_1529")]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="slug",
            field=models.SlugField(default="", editable=False, unique=False),
        )
    ]
