# Generated by Django 2.1.11 on 2020-01-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("career", "0018_gen_slug")]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="slug",
            field=models.SlugField(editable=False, unique=True, max_length=100),
        )
    ]
