# Generated by Django 2.2.28 on 2025-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0021_auto_20200914_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="is_displayed",
            field=models.BooleanField(default=True, verbose_name="is displayed"),
        ),
    ]
