# Generated by Django 2.2.28 on 2025-08-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0022_joblisting_is_displayed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="is_displayed",
            field=models.BooleanField(default=True, verbose_name="Show on website"),
        ),
    ]
