# Generated by Django 2.2.28 on 2025-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0023_auto_20250829_1351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblisting",
            name="from_year",
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="to_year",
        ),
        migrations.AddField(
            model_name="joblisting",
            name="from_grade",
            field=models.PositiveIntegerField(default=1, verbose_name="from grade"),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="to_grade",
            field=models.PositiveIntegerField(default=5, verbose_name="to grade"),
        ),
    ]
