# Generated by Django 1.10.2 on 2016-10-04 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20150506_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=1, verbose_name='prioritet'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
