version: '2'

services:
  postgres:
    image: 'postgres:10'
    environment:
      - POSTGRES_USER=itdagene
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '127.0.0.1:6379:6379'
