[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
lines_after_imports = 2
skip_glob = [
    "**/templates/*",
    ".tox/*",
    "node_modules/*",
    "venv/*",
    "itdagene/assets/*",
    "itdagene/locale/*",
]
