# Generated by Django 1.10.2 on 2016-10-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20140930_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='priority',
            field=models.PositiveIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Very High. Will send email to administrators')], default=1, verbose_name='priority'),
        ),
    ]
