# Generated by Django 2.2.28 on 2024-08-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="name",
        ),
        migrations.AddField(
            model_name="photo",
            name="active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
    ]
