# Generated by Django 2.2.28 on 2025-05-03 15:24

from django.db import migrations, models

import itdagene.app.gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_auto_20240830_1438"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="photo",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                validators=[itdagene.app.gallery.models.validate_order],
                verbose_name="display_order",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
