# Generated by Django 2.2.28 on 2025-05-08 16:37

from django.db import migrations, models

import itdagene.app.gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_auto_20250503_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="order",
            field=models.PositiveIntegerField(
                default=1,
                unique=True,
                validators=[itdagene.app.gallery.models.validate_order],
                verbose_name="display_order",
            ),
        ),
    ]
