version: 2
jobs:
  tests:
    docker:
      - image: python:3.6
      - image: postgres
        environment:
          POSTGRES_USER: itdagene

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/base.txt" }}-{{ checksum "tox.ini" }}
      - run:
          name: install dependencies
          command: |
            pip install tox
            tox --notest

      - save_cache:
          paths:
            - ./.tox
          key: deps-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/base.txt" }}-{{ checksum "tox.ini" }}

      - run:
          name: isort
          command: |
            tox -e isort

      - run:
          name: flake8
          command: |
            tox -e flake8

      - run:
          name: yapf
          command: |
            tox -e yapf

      - run:
          name: Tests
          command: |
            tox -e py36
            tox -e coverage

  build-docker:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t itdagene/itdagene:$CIRCLE_BRANCH .
      - run: docker push itdagene/itdagene:$CIRCLE_BRANCH

workflows:
  version: 2
  on_push:
    jobs:
      - tests
      - build-docker:
          requires:
            - tests
          filters:
            branches:
              only:
                - prod
