version: 2
jobs:
  tests-python:
    docker:
      - image: python:3.7
      - image: postgres:10.6-alpine
        environment:
          POSTGRES_USER: itdagene

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/base.txt" }}-{{ checksum "tox.ini" }}
      - run:
          name: install dependencies
          command: |
            pip install tox
            tox --notest

      - save_cache:
          paths:
            - ./.tox
          key: deps-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/base.txt" }}-{{ checksum "tox.ini" }}

      - run:
          name: flake8
          command: |
            tox -e flake8

      - run:
          name: black
          command: |
            tox -e black

      - run:
          name: Tests
          command: |
            tox -e python3.7
            tox -e coverage

  tests-javascript:
    docker:
      - image: node:13
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: |
            yarn

      - save_cache:
          paths:
            - ./node_modules/
          key: deps-{{ checksum "yarn.lock" }}

      - run:
          name: build
          command: |
            yarn build


  build-docker:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t itdagene/itdagene:$CIRCLE_BRANCH .
      - run: docker push itdagene/itdagene:$CIRCLE_BRANCH

workflows:
  version: 2
  on_push:
    jobs:
      - tests-python
      - tests-javascript
      - build-docker:
          requires:
            - tests-python
            - tests-javascript
          filters:
            branches:
              only:
                - prod
