# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-29 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auto_20170908_1206"),
        ("core", "0023_auto_20161004_1437"),
    ]

    operations = []
