# Generated by Django 2.2.13 on 2021-08-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_auto_20210508_2206"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="hsp_intro",
            field=models.TextField(
                blank=True,
                default="",
                help_text=
                "Introduction of main collaborator to be displayed above video on front page",
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="hsp_poster",
            field=models.URLField(
                blank=True,
                help_text="URL to the image to display before video is played",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="hsp_video",
            field=models.URLField(
                blank=True,
                help_text="URL to the video introduction of main collaborator",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="view_hsp",
            field=models.BooleanField(
                default=False,
                help_text=
                "Should the main collaborator be displayed on the front page?<br/><br/>",
                verbose_name="view main collaborator",
            ),
        ),
    ]
