# Generated by Django 2.2.13 on 2021-08-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_auto_20210812_2111"),
        ("core", "0032_auto_20210811_1738"),
    ]

    operations = []
