# Generated by Django 2.2 on 2026-08-01

from datetime import time

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_user_linkedin"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="event_start_time",
            field=models.TimeField(
                default=time(10, 0), verbose_name="event start time"
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="program_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether the public program may be displayed.",
                verbose_name="program published",
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="venue",
            field=models.CharField(
                default="Realfagbygget, NTNU", max_length=255, verbose_name="venue"
            ),
        ),
    ]
