# Generated by Django 2.2 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_preference_program_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="stands_published",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Skal årets standkart og standplasseringer vises på nettsiden?"
                ),
                verbose_name="Vis stands",
            ),
        ),
    ]
