# Generated by Django 2.2.28 on 2026-08-03 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_preference_stands_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="event_start_time",
            field=models.TimeField(
                default=datetime.time(10, 0),
                verbose_name="Starttid for itDAGENE (nedtelling)",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="program_published",
            field=models.BooleanField(
                default=False,
                help_text="Skal programmet for itDAGENE vises på nettsiden?",
                verbose_name="Vis program",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="venue",
            field=models.CharField(
                default="Realfagbygget, NTNU", max_length=255, verbose_name="Sted"
            ),
        ),
    ]
