# Generated by Django 2.0.3 on 2018-04-12 17:53

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("company", "0020_auto_20180206_1156")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo_inverted",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to="company_logos/",
                verbose_name="logo_inverted",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_vector",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to="company_logos/",
                verbose_name="logo_vector",
            ),
        ),
    ]
