# Generated by Django 2.2.13 on 2021-01-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0023_keyinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyinformation",
            name="name",
            field=models.CharField(max_length=40,
                                   verbose_name="information name"),
        ),
        migrations.AlterField(
            model_name="keyinformation",
            name="value",
            field=models.CharField(max_length=200, verbose_name="value"),
        ),
    ]
