# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_auto_20161012_1952"),
        ("feedback", "0008_auto_20161004_1437"),
    ]

    operations = []
