# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_auto_20161012_1936"),
        ("events", "0004_auto_20161004_1437"),
    ]

    operations = []
