# Generated by Django 2.0.6 on 2018-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pages", "0002_auto_20161004_1437")]

    operations = [
        migrations.AddField(
            model_name="page",
            name="ingress",
            field=models.TextField(default="", verbose_name="ingress"),
        )
    ]
