# Generated by Django 2.1.11 on 2020-01-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_page_ingress"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_infopage",
            field=models.BooleanField(default=False, verbose_name="is an info page"),
        ),
    ]
