# Generated by Django 2.2.28 on 2023-08-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_page_is_infopage"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="video_file",
            field=models.FileField(
                blank=True, null=True, upload_to="pageVideos/", default=None
            ),
        ),
    ]
