# Generated by Django 2.2.28 on 2024-04-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='pageVideos/'),
        ),
    ]
