# Generated by Django 1.10.2 on 2016-10-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20141004_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Preference', verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='type',
            field=models.CharField(choices=[('beer', 'Beer'), ('wine', 'Wine')], default='beer', max_length=10, verbose_name='type'),
        ),
    ]
