# Generated by Django 2.2.28 on 2024-08-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_auto_20171231_1831"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replymeeting",
            name="is_attending",
            field=models.BooleanField(blank=True, null=True, verbose_name="attending"),
        ),
    ]
