# Generated by Django 2.2.13 on 2020-12-16 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0023_keyinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_saved', models.DateTimeField(editable=False)),
                ('slug', models.SlugField(blank=True, help_text='Slug for stand. Will be autogenerated if left empty', max_length=150, unique=True)),
                ('livestream_url', models.URLField(blank=True, verbose_name='Livestream link')),
                ('qa_url', models.URLField(blank=True, verbose_name='Q&A link')),
                ('chat_url', models.URLField(blank=True, verbose_name='Chat link')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_stand', to='company.Company', verbose_name='Company')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='digitalstand_creator', to=settings.AUTH_USER_MODEL)),
                ('saved_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='digitalstand_saved_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
