# Generated by Django 2.2 on 2026-08-01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0025_auto_20210508_2142"),
        ("core", "0036_preference_program_configuration"),
        ("stands", "0002_auto_20210104_1744"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandMapRelease",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("lock_version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stand_map_releases",
                        to="core.Preference",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_stand_map_releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-revision",),
                "permissions": (
                    ("publish_standmaprelease", "Can publish stand map release"),
                ),
                "unique_together": {("preference", "revision")},
            },
        ),
        migrations.CreateModel(
            name="StandMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("label", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("background", models.ImageField(upload_to="stand_maps/")),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maps",
                        to="stands.StandMapRelease",
                    ),
                ),
            ],
            options={"ordering": ("date",), "unique_together": {("release", "date")}},
        ),
        migrations.CreateModel(
            name="StandPlacement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stand_number", models.CharField(max_length=30)),
                (
                    "x_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "y_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("company_name", models.CharField(editable=False, max_length=140)),
                ("company_slug", models.SlugField(editable=False, max_length=150)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stand_map_placements",
                        to="company.Company",
                    ),
                ),
                (
                    "stand_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="stands.StandMap",
                    ),
                ),
            ],
            options={
                "ordering": ("stand_number",),
                "unique_together": {
                    ("stand_map", "stand_number"),
                    ("stand_map", "company"),
                    ("stand_map", "company_slug"),
                },
            },
        ),
        migrations.AddConstraint(
            model_name="standmaprelease",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="published"),
                fields=("preference",),
                name="stands_one_published_release_per_preference",
            ),
        ),
    ]
